#!/usr/bin/env python3
"""
Check what redirect URI is registered in OAuth app
And provide options for fixing it
"""

print("=" * 60)
print("OAuth Redirect URI Issue")
print("=" * 60)
print()
print("Tradovate requires redirect URIs to be registered in OAuth app settings.")
print()
print("Common issues:")
print("  1. Redirect URI not registered in OAuth app")
print("  2. Redirect URI format doesn't match exactly")
print("  3. Localhost redirect URIs might not be allowed")
print()
print("=" * 60)
print("Solution Options")
print("=" * 60)
print()
print("Option 1: Register the redirect URI")
print("  - Log into Tradovate (account with OAuth app)")
print("  - Go to Application Settings → API Access → OAuth Registration")
print("  - Edit OAuth app (Client ID: 8552)")
print("  - Add redirect URI: http://localhost:8082/auth/tradovate/callback")
print("  - Save")
print()
print("Option 2: Use a different redirect URI")
print("  - Check what redirect URI was originally registered")
print("  - Update code to use that URI instead")
print("  - Common: http://localhost:8082 or http://127.0.0.1:8082")
print()
print("Option 3: Use ngrok for public URL")
print("  - Use ngrok to create public URL")
print("  - Register ngrok URL as redirect URI")
print("  - Update code to use ngrok URL")
print()
print("=" * 60)
print("Quick Fix: Check Original Redirect URI")
print("=" * 60)
print()
print("When you registered the OAuth app, what redirect URI did you use?")
print("Common values:")
print("  - http://localhost:8082")
print("  - http://127.0.0.1:8082")
print("  - http://localhost:8082/")
print()
print("We can update the code to use whatever URI is registered!")

