#!/usr/bin/env python3
"""
Check OAuth URL format - compare with TradersPost
"""

CLIENT_ID = "8552"
REDIRECT_URI = "http://localhost:8082"

print("=" * 60)
print("OAuth URL Format Check")
print("=" * 60)
print()
print("TradersPost uses: https://trader.tradovate.com/welcome")
print("And shows:")
print("  - 'Sign In with Tradovate'")
print("  - 'to continue to TradersPost Production Env'")
print("  - Permissions list")
print("  - Login form")
print()
print("Our OAuth URL:")
print("-" * 60)

# Current format
oauth_url = f"https://trader.tradovate.com/welcome?client_id={CLIENT_ID}&redirect_uri={REDIRECT_URI}&response_type=code&scope=read+write&state=4"
print(f"  {oauth_url}")
print()
print("This should show:")
print("  - 'Sign In with Tradovate'")
print("  - 'to continue to test' (your app name)")
print("  - Permissions list")
print("  - Login form")
print()
print("=" * 60)
print("Possible Issues")
print("=" * 60)
print()
print("1. Scope format")
print("   - Current: scope=read+write")
print("   - Try: scope=read,write or scope=read write")
print()
print("2. Redirect URI encoding")
print("   - Current: redirect_uri=http://localhost:8082")
print("   - Should be URL encoded: redirect_uri=http%3A%2F%2Flocalhost%3A8082")
print()
print("3. Missing parameters")
print("   - Maybe need: app_name, app_id, or other parameters")
print()
print("4. OAuth app configuration")
print("   - App name: 'test'")
print("   - Make sure it's active/enabled")
print("   - Check if permissions are set correctly")
print()
print("=" * 60)
print("Next Steps")
print("=" * 60)
print()
print("1. Visit the OAuth URL in your browser:")
print(f"   {oauth_url}")
print()
print("2. Check what you see:")
print("   - Do you see 'to continue to test'?")
print("   - Do you see permissions list?")
print("   - Or just login form?")
print()
print("3. If you see login form only:")
print("   - The OAuth request might not be recognized")
print("   - Try logging in first, then check again")
print()
print("4. After logging in:")
print("   - You should see the same page")
print("   - But with 'Authorize' or 'Login' button")
print("   - Click it to complete authorization")

