#!/usr/bin/env python3
"""
Debug OAuth callback - check what URL Tradovate redirects to
"""

print("=" * 60)
print("OAuth Callback Debugging")
print("=" * 60)
print()
print("Issue: Tradovate is NOT redirecting back to your app")
print()
print("What to check:")
print("=" * 60)
print()
print("1. Check Browser URL After Authorization")
print("   - After clicking 'Authorize', what URL are you on?")
print("   - Look at the browser address bar")
print("   - Does it say http://localhost:8082?code=...?")
print("   - Or does it redirect somewhere else?")
print()
print("2. Check Browser Console")
print("   - Open browser Developer Tools (F12)")
print("   - Go to Console tab")
print("   - Look for any errors")
print("   - Check Network tab for failed requests")
print()
print("3. Check OAuth App Settings")
print("   - Log into Tradovate")
print("   - Go to Application Settings → API Access → OAuth Registration")
print("   - Check Client ID: 8552")
print("   - Verify Redirect URI is EXACTLY: http://localhost:8082")
print("   - Make sure there's no trailing slash or path")
print()
print("4. Try Different Redirect URI")
print("   - Tradovate might not accept localhost")
print("   - Try using ngrok for a public URL")
print("   - Or use 127.0.0.1 instead of localhost")
print()
print("=" * 60)
print("Next Steps")
print("=" * 60)
print()
print("After you click 'Authorize' on Tradovate:")
print("  1. Check what URL you end up on")
print("  2. Check browser console for errors")
print("  3. Tell me what you see!")
print()
print("The callback should redirect to: http://localhost:8082?code=ABC123...")
print("But it seems like it's not happening.")

